name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      -
        name: Set up Snapcraft
        run: |
          sudo apt-get -yq --no-install-suggests --no-install-recommends install snapcraft
      -
        name: Snapcraft Login
        if: success() && startsWith(github.ref, 'refs/tags/v')
        env:
          SNAPCRAFT_LOGIN: ${{ secrets.snapcraft_token }}
        run: |
          snapcraft login --with <(echo "$SNAPCRAFT_LOGIN")
      -
        name: Dockerhub Login
        run: |
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username '${{ secrets.DOCKER_USERNAME }}' --password-stdin
      -
        name: GCC multilib
        run: |
          sudo apt-get install gcc-multilib g++-multilib
      -
        name: OSXCross for CGO Support
        run: |
          pwd
          mkdir ../plenti-osxcross
          git clone https://github.com/plentico/plenti-osxcross.git ../plenti-osxcross/target
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --debug
          key: ${{ secrets.YOUR_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
